print('Cozonaci ca la mama acasa')
print('Pretul unui cozonac este 5 lei')
fn=input('Prenumele:')
sn=input('Numele de familie: ')
adr=input('Adresa de livrare:')
cz=int(input('Cantitatea de cozonaci:'))
print('Cost cozonaci: ' + str(5 * cz) +'lei')
print('Livrarea costa 15 lei')
print('costul total este: ' + str(15 + 5 * cz) + 'lei')
print('Adresa de livrare este: '+ adr)
print('Prenumele: ' + fn )
print('Numele de familie: '+ sn)
print('Comanda dumneavoastra va fi livrata in 2 zile ')

